=head1 OmniPITR - omnipitr-cleanup

=head2 USAGE

/some/path/omnipitr/bin/omnipitr-cleanup [options] %r

Options:

=over

=item --archive (-a)

Where archived wal segments are kept.

Check L<Archive specification> for more details.

=item --log (-l)

Name of logfile (actually template, as it supports %% L<strftime(3)>
markers. Unfortunately due to the %x usage by PostgreSQL, We cannot use %%
macros directly. Instead - any occurence of ^ character in log dir will be first
changed to %, and later on passed to strftime.

=item --pid-file

Name of file to use for pidfile. If it is specified, than only one copy of
I<omnipitr-cleanup> (with this pidfile) can run at the same time.

Trying to run second copy of I<omnipitr-cleanup> will result in an error.

=item --verbose (-v)

Log verbosely what is happening.

=back

=head2 DESCRIPTION

Call to I<omnipitr-cleanup> should be in I<archive_cleanup_command> variable in
I<recovery.conf>.

Which options should be given depends only on installation, but generally you
will need:

=over

=item * --archive

=item * --log

=back

And of course the %r at the end.

This script is used only in cases of streaming replication, as in case of
wal-file based replication L<omnipitr-restore> can remove obsolete wal files.

=head3 Archive specification

If the wal segments are compressed you have to prefix archive path with
compression type followed by '=' sign.

Allowed compression types:

=over

=item * gzip

Used file extension is .gz

=item * bzip2

Used file extension is .bz2

=item * lzma

Used file extension is .lzma

=back

=head2 EXAMPLES

=head3 Minimal setup:

    archive_cleanup_command='/.../omnipitr-cleanup -l /var/log/omnipitr/cleanup.log -a /mnt/wal_restore/ %r'

=head3 Minimal setup, for gzip-compressed archives:

    archive_cleanup_command='/.../omnipitr-cleanup -l /var/log/omnipitr/cleanup.log -a gzip=/mnt/wal_restore/ %r'

=head2 COPYRIGHT

The OmniPITR project is Copyright (c) 2009-2012 OmniTI. All rights reserved.

