
=head1 OmniPITR

=head2 TODO

Even while developing first version of the OmniPITR, we know there are things
that could be improved. But first things first - we have to finish development
of base functionality before starting work on new stuff.

Here are the already known about missing features:

=over

=item * Ability to use %r in omnipitr-restore instead of relying on
pg_controldata

While definitely good thing, we will still keep code to use pg_controldata as %r
is not available in 8.2.

=item * Provide support for --help option

Well, it can be helpful to avoid having to type another command to get to docs

=item * Add support for config file

This has the benefit over command line options that it lets you change the
options without Pg restart (in omnipitr-restore case at least).

=item * Deliver to multiple destinations in parallel

When delivering wal segments to slave server, and to backup destination - we can
reduce the time it takes, by delivering it in parallel.

=item * Add option to provide custom options to rsync and other external
programs

This is required in case we are running in situation where rsync is not in PATH
on B<remote> end of replication.

=item * Add a way to specify "primary" destination for wal segments.

This would be useful if you have WAL-slave in the same network, and additional
slave, on a network link that can be down. Problems with non-primary
destinations wouldn't stop replication to primary destinations.

=item * Make temp directories inside given temp-dir, based on pid and/or random
values - to allow easy running (for example) 2 slaves on the same machine.

=item * Make it possible to provide multiple sources for omnipitr-restore

=item * Add specialized program to serve as archive_cleanup_command - with
support for compressed walarchive, and pausing removal

=item * Add option for omnipitr-restore to let it be used for
streaming-replication setups (i.e. fail on missing file, instead of waiting for
next one)

=back

=head2 COPYRIGHT

The OmniPITR project is Copyright (c) 2009-2010 OmniTI. All rights reserved.
